### ISSUE TITLE
yolov3+FCOS training and testing 

### ISSUE THREAD

**Issue by abhigoku10** [duanzhiihao/myDetection#5]
@duanzhiihao  thanks for sharing the source code . can you please point out the Yolov3+FCOS training and testing pipeline 
Thansk in advance

**Comment by duanzhiihao** [comment]
Hi, unfortunately, this repository is not under active maintenance and I forget where did I put yolov3 + FCOS config file, so I cannot easily provide you with the pipeline.

I recommend you read the code and figure it out (which could be very tedious). Maybe a better way is to look at popular object detection repositories like mmdetection.
